// Every UI string, Hebrew (default, RTL) and English.
export const STRINGS = {
  he: {
    startFs: 'מסך מלא ויאללה', startGo: 'המשך', iosHint: 'באייפון: שתפו ← "הוספה למסך הבית" כדי לשחק במסך מלא.',
    authTitle: 'הרשמה לטבלת השיאים', authDesc: 'בוחרים כינוי וסיסמה, והזמנים שלכם נכנסים לטבלה המשותפת של כולם.',
    register: 'הרשמה', login: 'כניסה', nickname: 'כינוי (2–12 תווים)', password: 'סיסמה (6 תווים לפחות)', playOffline: 'לשחק בלי חיבור',
    leaderboard: 'טבלת שיאים', logout: 'יציאה', loggedAs: 'מחובר/ת בתור {n}', tourneyTab: 'טורניר',
    boardLoading: 'טוען…', boardEmpty: 'עוד אין תוצאות. תהיו הראשונים!', boardOffline: 'אין חיבור לטבלת השיאים כרגע.',
    boardOff: 'טבלת השיאים המשותפת עוד לא הוגדרה (leaderboard-config.js).', yourBest: 'השיא שלך: מקום {r}',
    onlineNew: 'נכנס לטבלה המשותפת: מקום {r}!', onlineKept: 'השיא שלך בטבלה נשאר {b} (מקום {r})', onlineFail: 'לא הצלחנו לשלוח לטבלה',
    errName: 'הכינוי צריך 2–12 תווים', errNameChars: 'בכינוי מותר רק אותיות, ספרות, רווח, נקודה, מקף וקו תחתון', errPass: 'הסיסמה צריכה לפחות 6 תווים',
    errTaken: 'הכינוי הזה כבר תפוס', errLogin: 'כינוי או סיסמה לא נכונים', errTooMany: 'יותר מדי ניסיונות, נסו שוב בעוד רגע',
    errNetwork: 'אין חיבור לאינטרנט', errGeneric: 'משהו השתבש, נסו שוב', errMissing: 'צריך כינוי וסיסמה',
    loading: 'טוען…', loadFail: 'משהו השתבש בטעינה. רעננו את הדף.', noWebGL: 'הדפדפן הזה לא תומך ב־WebGL, ולכן אי אפשר להריץ את המשחק.',
    tournament: 'טורניר', timeTrial: 'נגד השעון', practice: 'אימון', settings: 'הגדרות', back: 'חזרה', start: 'יוצאים לדרך!',
    tourneyDesc: '8 מרוצים ברצף. הזמן שנשאר עובר למרוץ הבא, וכשהשעון מגיע לאפס זה נגמר.',
    difficulty: 'רמת קושי', easy: 'קל', normal: 'רגיל', hard: 'קשה',
    mirror: 'מצב מראה', mirrorLocked: 'סיימו את הטורניר כדי לפתוח את מצב המראה', bestScore: 'שיא ניקוד',
    chooseRaceTT: 'נגד השעון: בחרו מרוץ', chooseRacePr: 'אימון: בחרו מרוץ', locked: 'נעול', lockedHint: 'סיימו את המרוץ הקודם', best: 'שיא',
    music: 'מוזיקה', sfx: 'אפקטים', language: 'שפה', graphics: 'גרפיקה', qAuto: 'אוטומטי', qHigh: 'גבוהה', qLow: 'חסכונית',
    showFps: 'הצגת FPS', invertMouse: 'היפוך עכבר', reducedMotion: 'הפחתת תנועה', fullscreen: 'מסך מלא',
    paused: 'הפסקה', resume: 'המשך', restart: 'מרוץ מחדש', quit: 'יציאה לתפריט',
    raceOf: 'מרוץ {n}/8', checkpoint: 'צ׳קפוינט!', timesUp: 'נגמר הזמן!', finish: 'הגעתם!', go: 'סעו!',
    time: 'זמן', remaining: 'נשאר בשעון', parBonus: 'בונוס זמן יעד', rivalBonus: 'הפלת יריב', score: 'ניקוד', total: 'ניקוד כולל',
    continue: 'המשך', retry: 'שוב', menu: 'לתפריט', newBest: 'שיא חדש!',
    bronze: 'ארד', silver: 'כסף', gold: 'זהב', acorn: 'בלוט הזהב', noMedal: 'בלי מדליה הפעם, נסו שוב',
    target: 'יעד', allMedals: 'כל המדליות שלכם!', skip: 'הקישו לדילוג',
    tourneyDone: 'אלופים! סיימתם את הטורניר', mirrorUnlocked: 'מצב מראה נפתח!', racesDone: 'סיימתם {n} מתוך 8 מרוצים',
    timeAdded: '+{s} שנ׳ לשעון', practiceLabel: 'אימון', ttLabel: 'נגד השעון',
    controlsHint: 'חיצים או WASD לגלגול · רווח לבלימה · R חזרה לצ׳קפוינט · Esc להפסקה',
    controlsHintTouch: 'גררו בכל מקום על המסך כדי לגלגל · כפתור הבלם עוצר',
    brake: 'בלם', rival: 'יריב הופל! +2000', parHit: 'מתחת לזמן היעד!', ghost: 'רוח: השיא שלכם', seconds: 'שנ׳',
  },
  en: {
    startFs: 'Full screen & play', startGo: 'Continue', iosHint: 'On iPhone: Share → "Add to Home Screen" to play full screen.',
    authTitle: 'Join the leaderboard', authDesc: 'Pick a nickname and password and your times go on the shared board for everyone.',
    register: 'Sign up', login: 'Log in', nickname: 'Nickname (2–12 characters)', password: 'Password (6+ characters)', playOffline: 'Play offline',
    leaderboard: 'Leaderboard', logout: 'Log out', loggedAs: 'Signed in as {n}', tourneyTab: 'Tournament',
    boardLoading: 'Loading…', boardEmpty: 'No results yet. Be the first!', boardOffline: 'The leaderboard is unreachable right now.',
    boardOff: 'The shared leaderboard is not set up yet (leaderboard-config.js).', yourBest: 'Your best: rank {r}',
    onlineNew: 'On the shared board: rank {r}!', onlineKept: 'Your board best stays {b} (rank {r})', onlineFail: 'Could not reach the leaderboard',
    errName: 'Nickname must be 2–12 characters', errNameChars: 'Letters, digits, space, dot, dash and underscore only', errPass: 'Password needs at least 6 characters',
    errTaken: 'That nickname is taken', errLogin: 'Wrong nickname or password', errTooMany: 'Too many attempts, try again shortly',
    errNetwork: 'No internet connection', errGeneric: 'Something went wrong, try again', errMissing: 'Nickname and password are required',
    loading: 'Loading…', loadFail: 'Something went wrong while loading. Please refresh.', noWebGL: 'This browser does not support WebGL, so the game cannot run.',
    tournament: 'Tournament', timeTrial: 'Time Trial', practice: 'Practice', settings: 'Settings', back: 'Back', start: "Let's roll!",
    tourneyDesc: '8 races in a row. Leftover time carries into the next race, and when the clock hits zero it is over.',
    difficulty: 'Difficulty', easy: 'Easy', normal: 'Normal', hard: 'Hard',
    mirror: 'Mirror mode', mirrorLocked: 'Finish the tournament to unlock Mirror mode', bestScore: 'Best score',
    chooseRaceTT: 'Time Trial: pick a race', chooseRacePr: 'Practice: pick a race', locked: 'Locked', lockedHint: 'Finish the previous race', best: 'Best',
    music: 'Music', sfx: 'Sound effects', language: 'Language', graphics: 'Graphics', qAuto: 'Auto', qHigh: 'High', qLow: 'Battery saver',
    showFps: 'Show FPS', invertMouse: 'Invert mouse', reducedMotion: 'Reduced motion', fullscreen: 'Fullscreen',
    paused: 'Paused', resume: 'Resume', restart: 'Restart race', quit: 'Quit to menu',
    raceOf: 'Race {n}/8', checkpoint: 'Checkpoint!', timesUp: "TIME'S UP!", finish: 'Finish!', go: 'GO!',
    time: 'Time', remaining: 'Left on clock', parBonus: 'Par bonus', rivalBonus: 'Rival knock-offs', score: 'Score', total: 'Total score',
    continue: 'Continue', retry: 'Retry', menu: 'Menu', newBest: 'New best!',
    bronze: 'Bronze', silver: 'Silver', gold: 'Gold', acorn: 'Golden Acorn', noMedal: 'No medal this time, try again',
    target: 'Target', allMedals: 'Every medal is yours!', skip: 'Tap or press any key to skip',
    tourneyDone: 'Champions! Tournament complete', mirrorUnlocked: 'Mirror mode unlocked!', racesDone: 'You finished {n} of 8 races',
    timeAdded: '+{s}s on the clock', practiceLabel: 'Practice', ttLabel: 'Time Trial',
    controlsHint: 'Arrows or WASD to roll · Space to brake · R back to checkpoint · Esc to pause',
    controlsHintTouch: 'Drag anywhere to roll · Hold the brake button to stop',
    brake: 'Brake', rival: 'Rival knocked off! +2000', parHit: 'Under par!', ghost: 'Ghost: your best', seconds: 's',
  },
};
